### ISSUE TITLE
very useful

### ISSUE THREAD

**Issue by joeblew99** [pope/polymer-strands#1]
Is this still working, now that polymer 1.2 is out ?

nice idea this.

**Comment by pope** [comment]
First, thanks.

Second, It still works with polymer 1.2. polymer-strands works by finding all of the HTML imports to build the dependencies. So no nothing changed with imports and this it still works.

**Comment by joeblew99** [comment]
OK thanks.

I will give it a shot.
Here is what I am thinking of using it for:

I need to know the graph, but also to hash each dependency element so it can work on a dumb CDN.
